---
- name: Download Michigan OSM data
  get_url: url=http://download.geofabrik.de/north-america/us/michigan-latest.osm.pbf
           dest={{ osm_data_dir }}/michigan-latest.osm.pbf
- name: Import Michigan OSM data (takes a long time)
  shell: /usr/local/bin/osm2pgsql --database osm --slim --cache 1024 --cache-strategy=dense --number-processes=1 --hstore {{ osm_data_dir }}/michigan-latest.osm.pbf && touch /tmp/import-michigan-osm.success
         creates=/tmp/import-michigan-osm.success
  sudo_user: postgres

